# Generated by Django 5.2.4 on 2025-09-29 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_count', models.IntegerField()),
                ('study_time', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('client_timestamp', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Log',
                'verbose_name_plural': 'Learning Logs',
                'db_table': 'learning_logs',
                'unique_together': {('user', 'timestamp')},
            },
        ),
    ]
