# Generated by Django 5.2.4 on 2025-09-29 03:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_aggregator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='learninglog',
            index=models.Index(fields=['user', 'timestamp'], name='learning_lo_user_id_03875d_idx'),
        ),
    ]
